/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b6ff425c-7835-44a8-be80-75aae415d9a6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_TRXoBXWLh",
    "aws_user_pools_web_client_id": "1v5p135h1h9t9ag4nifa9ph1bo",
    "oauth": {},
    "aws_user_files_s3_bucket": "poze154410-prod",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://oui5afrv65f3rnsieofvvpxmi4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-kwj2i7mttvgjbnuw22mvck54pm"
};


export default awsmobile;
